version: '3.8'
services:
  cake-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cake_mngr_db"
#    volumes:
#      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  cakemanager-service:
    build:
      context: .
    depends_on:
      cake-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker_compose"
    networks:
      backend:
        aliases:
          - "cakemanager-service"
networks:
  backend:
    driver: bridge